hmac_md5: replace caddr_t with void pointer
Replace caddr_t, which is a BSD extension, with void pointers, as the
former will cause signess warnings with modern GCCs.

Fixes the following warnings/errors:

hmac_md5.c: In function ‘MD5Final’:
hmac_md5.c:289:24: error: passing argument 2 of ‘MD5Update’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  289 |     MD5Update(context, PADDING, padLen);
      |                        ^~~~~~~
hmac_md5.c:243:56: note: expected ‘unsigned char *’ but argument is of type ‘const unsigned char *’
  243 | static void MD5Update(MD5_CTX *context, unsigned char *input,
      |                                         ~~~~~~~~~~~~~~~^~~~~
hmac_md5.c: In function ‘hmac_md5’:
hmac_md5.c:360:14: error: pointer targets in passing argument 1 of ‘MD5Final’ differ in signedness [-Werror=pointer-sign]
  360 |     MD5Final(digest, &context);          /* finish up 1st pass */
      |              ^~~~~~
      |              |
      |              caddr_t {aka char *}
hmac_md5.c:278:36: note: expected ‘unsigned char *’ but argument is of type ‘caddr_t’ {aka ‘char *’}
  278 | static void MD5Final(unsigned char digest[16], MD5_CTX *context)
      |                      ~~~~~~~~~~~~~~^~~~~~~~~~
hmac_md5.c:367:25: error: pointer targets in passing argument 2 of ‘MD5Update’ differ in signedness [-Werror=pointer-sign]
  367 |     MD5Update(&context, digest, 16);     /* then results of 1st
      |                         ^~~~~~
      |                         |
      |                         caddr_t {aka char *}
hmac_md5.c:243:56: note: expected ‘unsigned char *’ but argument is of type ‘caddr_t’ {aka ‘char *’}
  243 | static void MD5Update(MD5_CTX *context, unsigned char *input,
      |                                         ~~~~~~~~~~~~~~~^~~~~
hmac_md5.c:369:14: error: pointer targets in passing argument 1 of ‘MD5Final’ differ in signedness [-Werror=pointer-sign]
  369 |     MD5Final(digest, &context);          /* finish up 2nd pass */
      |              ^~~~~~
      |              |
      |              caddr_t {aka char *}
hmac_md5.c:278:36: note: expected ‘unsigned char *’ but argument is of type ‘caddr_t’ {aka ‘char *’}
  278 | static void MD5Final(unsigned char digest[16], MD5_CTX *context)
      |                      ~~~~~~~~~~~~~~^~~~~~~~~~

Signed-off-by: Jonas Gorski <jonas.gorski@gmail.com>
Signed-off-by: Tomáš Kyzlink <tkyzlink@dtitech.cz>